### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/packagist-api#45]
Could anyone tag a new release now that #43 is merged?
(ping @umpirsky @MarioBlazek @Einenlum)

**Comment by chadicus** [comment]
If possible, i would like to see #39 and #40  merged before the release.

**Comment by MarioBlazek** [comment]
@m1guelpf I would be very happy to do so, but I can't I'm not the owner of this repo. Maybe would guys from KnpLabs want to give permissions someone from community ? @docteurklein @umpirsky what do you think ?

**Comment by NiR-** [comment]
Enjoy! :)
