### ISSUE TITLE
Cannot limit package search

### ISSUE THREAD

**Issue by garak** [KnpLabs/packagist-api#65]
The current implementation of `search` method in Client class is returning all searched packages.
This can be undesirable in a situation where such search needs to be liimted.

My proposal is to add a new boolan parameter, with a sensible default (to keep back-compatibility):
```php
public function search($query, array $filters = array(), $limit = false)
{
    $results = $response = array();
    $filters['q'] = $query;
    $url = '/search.json?' . http_build_query($filters);
    $response['next'] = $this->url($url);

    do {
        $response = $this->request($response['next']);
        $response = $this->parse($response);
        $createResult = $this->create($response);
        if (!is_array($createResult)) {
            $createResult = [$createResult];
        }
        $results = array_merge($results, $createResult);
    } while (isset($response['next']) && !$limit);

    return $results;
}
```

I can open a PR, if you agree.

**Comment by robbieaverill** [comment]
Are you able to provide an example of the problem?

**Comment by garak** [comment]
> Are you able to provide an example of the problem?

Of course: this URL https://poser.pugx.org/search_packagist?name=symf is using search method and, as you can see, is getting 1000 results.
Source code is here: https://github.com/PUGX/badge-poser/blob/master/src/Controller/PackagistController.php#L23

**Comment by robbieaverill** [comment]
How many do you expect it should return?

**Comment by robbieaverill** [comment]
By the way, I'm happy to review a pull request if you want to make one. I'm just trying to understand the situation a little more clearly.
