### ISSUE TITLE
Get require info by package.json

### ISSUE THREAD

**Issue by JellyBellyDev** [KnpLabs/packagist-api#71]
Hi,
would it be possible to add to the library the possibility to retrieve information such as 
```json
"php": "^8.0",
"ext-gd": "*",
```
present in the require section of the composer.json file?

maybe even the full list of requires, like packagist?

![Schermata 2021-08-23 alle 17 04 05](https://user-images.githubusercontent.com/190820/130470685-a387ba29-19ba-4e64-85e5-e69f0fbdc6c7.png)

WDYT?
Thanks

**Comment by JellyBellyDev** [comment]
Maybe we can use the new api [composer v2 metadata](https://packagist.org/apidoc#get-package-data)?

**Comment by robbieaverill** [comment]
Hi @JellyBellyDev, this sounds like a good addition. Are you interested in making a pull request to add it?

**Comment by JellyBellyDev** [comment]
> Hi @JellyBellyDev, this sounds like a good addition. Are you interested in making a pull request to add it?

Ok! I try!

**Comment by JellyBellyDev** [comment]
I studied the library and I think that this library should not expose one method to retrieve the require deps because these info are different for distinct version of the library.
My opinion is that the user get the specific `Version` and retrieve the require info!
WDYT?

**Comment by robbieaverill** [comment]
Yes that makes sense to me

**Comment by JellyBellyDev** [comment]
Great, then I close!
