### ISSUE TITLE
CI is missing

### ISSUE THREAD

**Issue by stof** [KnpLabs/packagist-api#73]
This repo was using Travis, but this is not working anymore due to the end of free open-source support on Travis. As a result, there is no CI anymore.

And for instance, the specs are broken in the merged PR #72

**Comment by robbieaverill** [comment]
Interesting, I didn't realise that Travis had fully stopped support for free OSS builds. I'll look at switching to something else soon.

**Comment by stof** [comment]
Well, they give you some non-renewable free credits. Once you run out of them, you need either to pay, or to call their support to request more free credits (which are also not renewable, and would probably be rejected in that case due to KnpLabs being a company).
I suggest using GitHub Actions, which is what we did for KnpMenu for instance.
