### ISSUE TITLE
Description can be empty

### ISSUE THREAD

**Issue by garak** [KnpLabs/packagist-api#80]
See for example https://packagist.org/packages/magefan/module-community
This is currently unsupported in Package object since `$description` is cast as string (it should be ?string instead).

**Comment by robbieaverill** [comment]
Thanks for the report. Is this causing a runtime error when importing this package? Changing the method signature would necessitate a new major version release, so I'd prefer to cast the description as a string, even when empty/null, when we hydrate Package objects. This could then be released as a patch change. What do you think about this approach?

**Comment by garak** [comment]
I think that forcing an empty string instead of null can be enough for now.

**Comment by robbieaverill** [comment]
Fixes in [v1.7.2](https://github.com/KnpLabs/packagist-api/releases/tag/v1.7.2)

**Comment by JellyBellyDev** [comment]
@robbieaverill please can you apply this patch also in `2.x-dev`? Thanks!

**Comment by robbieaverill** [comment]
It's been merged up already, I will get #79 merged too then tag another beta

**Comment by robbieaverill** [comment]
Hi @JellyBellyDev, @garak, etc., this change is now available in [v2.0.0-rc1](https://github.com/KnpLabs/packagist-api/releases/tag/v2.0.0-rc1). Please let me know if you have any problems with this version.
