### ISSUE TITLE
Downloads can be empty

### ISSUE THREAD

**Issue by garak** [KnpLabs/packagist-api#84]
This is the same problem detected in #80, but for `$downloads` property.

**Comment by JellyBellyDev** [comment]
use case, package: `happyr/translation-bundle`
```php
Cannot assign null to property Packagist\Api\Result\Package::$downloads of type Packagist\Api\Result\Package\Downloads
```

**Comment by robbieaverill** [comment]
That example package shows that `favers` can be null too, will adjust that also
